# ==================================== 全局设置 ====================================

## 顶部预览大图（不知道为什么，设置这个属性貌似没起到作用）
banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png

## Hexo的网页图标
favicon: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/icon.png

## 是否强制全局HTTPS
force_https: true

## 自定义JS
custom_js:
  ### 鼠标点击出小爱心❤
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/love.js
  ### 鼠标跟随小星星
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/xiaoxingxing.js
  ### 小雪花飘落
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/xiaoxuehua.js
  ### 动态彩带
  - //cdn.jsdelivr.net/gh/bynotes/texiao/source/js/caidai.js


## 暗黑模式设置
dark_mode:
  enable: true
  default: auto

## 导航栏设置
navbar:
  ### 博客标题
  blog_title: SnowDream的博客
  ### 导航菜单
  menu:
    - { key: '首页', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: '归档', link: '/archives', icon: 'iconfont icon-books' }
    - { key: '分类', link: '/categories', icon: 'iconfont icon-th-large'}
    - { key: '标签', link: '/tags/', icon: 'iconfont icon-tags-fill'}
    - { key: '关于', link: '/about/', icon: 'iconfont icon-user-fill'}
    - { key: '友链', link: '/links/', icon: 'iconfont icon-link-fill' }

## 关于页设置
about:
  ## 关于页的顶部预览图
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png
  ### 你的头像
  avatar: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/yuuki.jpg
  ### 你的昵称
  name: "SnowDream"
  ### 个人简介
  intro: "我只想在雪夜的樱花树下做个好梦"
  ### 外链设置
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/SnowDreamXUE', tip: 'GitHub' }
    - { class: 'iconfont icon-csdn', link: 'https://blog.csdn.net/SnowDreamXUE?type=blog', tip: 'CSDN' }

## 友情链接页设置
links:
  ### 友情链接页的顶部预览图
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png
  items:
    - {
      title: 'SnowDream',
      intro: 'SnowDream 的 CSDN',
      link: 'https://blog.csdn.net/SnowDreamXUE?type=blog',
      avatar: 'https://cdn.jsdelivr.net/gh/SnowDreamXUE/cnblog_resources@main/images/yuuki.jpg'
    }
    - {
        title: '小城寒风',
        intro: '驻足现实，仰望星空，率性而活',
        link: 'https://blog.atago.moe',
        avatar: 'https://blog.atago.moe/wp-content/uploads/2023/08/头像atago512隐写.png'
    }
    - {
      title: 'Fluid Docs',
      intro: 'Fluid 主题使用指南',
      link: 'https://hexo.fluid-dev.com/docs/',
      avatar: '/img/favicon.png'
    }
  ### 默认头像
  default_avatar: https://cdn.jsdelivr.net/gh/SnowDreamXUE/cnblog_resources@main/images/yuuki.jpg

## 标签页设置
tag:
  ### 标签页的顶部预览图
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png

## 分类页设置
category:
  ### 分类页的顶部预览图
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png

## 归档页设置
archive:
  ### 归档页的顶部预览图
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png

## 懒加载设置
lazyload:
  ### 是否启用懒加载
  enable: true
  ### 为 true 时，懒加载仅在文章页生效，如果自定义页面需要使用，可以在 Front-matter (opens new window)里指定
  onlypost: false
  ### 触发加载的偏移倍数，基数是视窗高度（即提前 N 屏高度触发加载），可根据部署环境的请求速度调节
  offset_factor: 2

## 全局字体设置
font:
  ### 全局字号
  font_size: 16px
  ### 全局字体族
  font_family: "Microsoft YaHei"
  ### 代码字号
  code_font_size: 85%

# ==================================== 首页设置 ====================================
index:
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png
  ## 打字机设置
  slogan:
    ### 是否启用打字机
    enable: true
    ### 打字机文字内容
    text: 喜欢雪且爱做梦
  ## 文章跳转方式 _blank：新标签页打开  _self：当前标签页打开
  post_url_target: _self
  ## 文章信息设置：可配置隐藏包括发布时间、分类、标签
  post_meta:
    date: true
    category: true
    tag: true

# ==================================== 文章页设置 ====================================
post:
  ## 统一给文章设置一个默认封面
  default_index_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png
  banner_img: https://snow-pic.oss-cn-guangzhou.aliyuncs.com/pic/background_2.png
  math:
    enable: true
    specific: false
    engine: mathjax
  ## 日期/字数/阅读时长/阅读数 设置
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: true
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: " YYYY 年 MM 月 DD 日 , a hh:mm , dddd"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
  ## 评论设置
  comments:
    enable: true
    type: valine


# ==================================== 代码块设置 ====================================
code:
  ## 是否开启复制代码的按钮
  copy_btn: true
  ## 高亮设置
  highlight:
    ### 是否开启代码高亮
    enable: true
    ### 是否开启行号
    line_number: true
    ### 选择生成高亮的库，可选项: highlightjs、prismjs，对应下面两组配置，高亮的配置说明具体见主题配置中的注释
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <div style="font-size: 0.85rem">
      <span id="timeDate">载入天数...</span>
      <span id="times">载入时分秒...</span>
      <script src="/js/duration.js"></script>
    </div>
  '
